apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tailchat-hpa
  namespace: gic-chathub
spec:
  maxReplicas: 30
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: tailchat
  targetCPUUtilizationPercentage: 10

  