{
 "title": "GIC ChatHub",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes / container_memory_available_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_filesystem_usage_bytes / container_filesystem_available_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Established Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "system_network_connections{state=\"ESTABLISHED\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}