apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
  namespace: gic-chathub
spec:
  serviceName: mongo
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      containers:
      - name: mongodb
        image: registry.deti/gic-chathub/mongo:latest
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/tailchat/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi